services:
    dev-nusalegal:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: dev-nusalegal
        image: dev-nusalegal:latest
        restart: always
        ports:
            - 3911:3001
        environment:
            TOKEN_SECRET: nusaLegalD1232!!@@@@2025
            TOKEN_EXPIRY: 5
            ALLOWED_ORIGINS: https://nusalegal.udaputera.com
