import type { Config } from 'tailwindcss'

export default <Config>{
  content: [
    "./app/components/**/*.{js,vue,ts}",
    "./app/layouts/**/*.vue",
    "./app/pages/**/*.vue",
    "./app/plugins/**/*.{js,ts}",
    "./app/app.vue",
    "./app/error.vue"
  ],
  theme: {
    extend: {},
  },
  plugins: [
    require('daisyui')
  ],
  daisyui: {
    themes: [
      {
        light: {
          ...require("daisyui/src/theming/themes")["light"],
          primary: "#8a63ff",
          "primary-focus": "#7c52e6",
          "primary-content": "#ffffff",
          secondary: "#ef476f",
          "secondary-focus": "#d63856",
          "secondary-content": "#ffffff",
          accent: "#118ab2",
          "accent-focus": "#0e7390",
          "accent-content": "#ffffff",
          neutral: "#3d4451",
          "neutral-focus": "#2a2e37",
          "neutral-content": "#ffffff",
          "base-100": "#ffffff",
          "base-200": "#f9fafb",
          "base-300": "#d1d5db",
          "base-content": "#1f2937",
          info: "#3abff8",
          "info-content": "#ffffff",
          success: "#36d399",
          "success-content": "#ffffff",
          warning: "#fbbd23",
          "warning-content": "#ffffff",
          error: "#f87272",
          "error-content": "#ffffff",
        },
        dark: {
          ...require("daisyui/src/theming/themes")["dark"],
          primary: "#8a63ff",
          "primary-focus": "#9b7fff",
          "primary-content": "#ffffff",
          secondary: "#ef476f",
          "secondary-focus": "#f16385",
          "secondary-content": "#ffffff",
          accent: "#118ab2",
          "accent-focus": "#2a9dbf",
          "accent-content": "#ffffff",
          neutral: "#2a2e37",
          "neutral-focus": "#3d4451",
          "neutral-content": "#ffffff",
          "base-100": "#1d1d1d",
          "base-200": "#2a2e37",
          "base-300": "#3d4451",
          "base-content": "#e5e5e5",
          info: "#3abff8",
          "info-content": "#ffffff",
          success: "#36d399",
          "success-content": "#ffffff",
          warning: "#fbbd23",
          "warning-content": "#000000",
          error: "#f87272",
          "error-content": "#ffffff",
        },
      },
    ],
  },
}
